services:
  backend:
    image: video-backend:0.2
    build:
      context: ./config/django_image
    env_file:
      - .env
    volumes:
      - ./src/django:/usr/src/app:delegated
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - red

  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - red

networks:
  red: